
/*
 ***************************************************************************
 *                  Mica - the Java(tm) Graphics Framework                 *
 ***************************************************************************
 * NOTICE: Permission to use, copy, and modify this software and its       *
 * documentation is hereby granted provided that this notice appears in    *
 * all copies.                                                             *
 *                                                                         *
 * Permission to distribute un-modified copies of this software and its    *
 * documentation is hereby granted provided that no fee is charged and     *
 * that this notice appears in all copies.                                 *
 *                                                                         *
 * SOFTWARE FARM MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE          *
 * SUITABILITY OF THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT  *
 * NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR  *
 * A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. SOFTWARE FARM SHALL NOT BE   *
 * LIABLE TO ANY PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR       *
 * CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE, MODIFICATION OR           *
 * DISTRIBUTION OF THIS SOFTWARE OR ITS DERIVATIVES.                       *
 *                                                                         *
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, AND THE AUTHORS AND      *
 * DISTRIBUTORS HAVE NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT,        *
 * UPDATES, ENHANCEMENTS, OR MODIFICATIONS.                                *
 *                                                                         *
 ***************************************************************************
 *   Copyright (c) 1997-2004 Software Farm, Inc.  All Rights Reserved.     *
 ***************************************************************************
 */


package com.swfm.mica;

/**----------------------------------------------------------------------------------------------
 * This class makes a 'edit' menu that is suitable for adding to a
 * MiEditorMenuBar. Each menu item has status bar and balloon help and
 * most have accelerators and mnemonics.
 * <p>
 * When a menu item is selected by the user one of the following commands
 * are generated:
 * <p>
 * <pre>
 *    Mi_UNDO_COMMAND_NAME
 *    Mi_REDO_COMMAND_NAME
 *    Mi_CUT_COMMAND_NAME
 *    Mi_COPY_COMMAND_NAME
 *    Mi_PASTE_COMMAND_NAME
 *    Mi_DELETE_COMMAND_NAME
 *    Mi_SELECT_ALL_COMMAND_NAME
 *    Mi_DESELECT_ALL_COMMAND_NAME
 *    Mi_DUPLICATE_COMMAND_NAME
 * </pre>
 * @version     %I% %G%
 * @author      Michael L. Davis
 * @release 	1.4.1
 * @module 	%M%
 * @language	Java (JDK 1.4)
 *----------------------------------------------------------------------------------------------*/
public class MiEditMenu extends MiEditorMenu implements MiiCommandNames, MiiMessages
	{
					/**------------------------------------------------------
	 				 * Constructs a new MiEditMenu, forwarding commands generated
					 * by this menu to an instance of MiEditMenuCommands.
					 * @see			MiEditMenuCommands
					 *------------------------------------------------------*/
	public				MiEditMenu(MiiCommandManager manager)
		{
		this(new MiEditMenuCommands(manager), manager);
		}
					/**------------------------------------------------------
	 				 * Constructs a new MiEditMenu which will send commands
					 * generated by the menu to the given command handler.
					 * @param handler	the command handler
					 * @see 		MiEditMenuCommands
					 *------------------------------------------------------*/
	public				MiEditMenu(
						MiiCommandHandler handler, 
						MiiCommandManager manager)
		{
		super(Mi_EDIT_MENU_DISPLAY_NAME, manager);

		setCommandHandler(handler);

		appendMenuItem(	Mi_UNDO_MENUITEM_DISPLAY_NAME, 		handler, 
								Mi_UNDO_COMMAND_NAME,
								Mi_UNDO_STATUS_HELP_MSG,
								Mi_NO_UNDO_STATUS_HELP_MSG,
								Mi_UNDO_BALLOON_HELP_MSG);

		appendMenuItem(	Mi_REDO_MENUITEM_DISPLAY_NAME, 		handler, 
								Mi_REDO_COMMAND_NAME,
								Mi_REDO_STATUS_HELP_MSG,
								Mi_NO_REDO_STATUS_HELP_MSG,
								Mi_REDO_BALLOON_HELP_MSG);
		appendSeparator();
		appendMenuItem( Mi_CUT_MENUITEM_DISPLAY_NAME, 		handler, 
								Mi_CUT_COMMAND_NAME,
								Mi_CUT_STATUS_HELP_MSG,
								Mi_NO_CUT_STATUS_HELP_MSG,
								Mi_CUT_BALLOON_HELP_MSG);

		appendMenuItem(	Mi_COPY_MENUITEM_DISPLAY_NAME, 		handler, 
								Mi_COPY_COMMAND_NAME,
								Mi_COPY_STATUS_HELP_MSG,
								Mi_NO_COPY_STATUS_HELP_MSG,
								Mi_COPY_BALLOON_HELP_MSG);

		appendMenuItem(	Mi_PASTE_MENUITEM_DISPLAY_NAME, 	handler, 
								Mi_PASTE_COMMAND_NAME,
								Mi_PASTE_STATUS_HELP_MSG,
								Mi_NO_PASTE_STATUS_HELP_MSG,
								Mi_PASTE_BALLOON_HELP_MSG);
		appendSeparator();
		appendMenuItem(	Mi_DELETE_MENUITEM_DISPLAY_NAME, 	handler, 
								Mi_DELETE_COMMAND_NAME,
								Mi_DELETE_STATUS_HELP_MSG,
								Mi_NO_DELETE_STATUS_HELP_MSG,
								Mi_DELETE_BALLOON_HELP_MSG);
		appendSeparator();
		appendMenuItem(	Mi_SELECT_ALL_MENUITEM_DISPLAY_NAME, 	handler, 
								Mi_SELECT_ALL_COMMAND_NAME,
								Mi_SELECT_ALL_STATUS_HELP_MSG,
								Mi_NO_SELECT_ALL_STATUS_HELP_MSG,
								Mi_SELECT_ALL_BALLOON_HELP_MSG);

		appendMenuItem(	Mi_DESELECT_ALL_MENUITEM_DISPLAY_NAME,	handler, 
								Mi_DESELECT_ALL_COMMAND_NAME,
								Mi_DESELECT_ALL_STATUS_HELP_MSG,
								Mi_NO_DESELECT_ALL_STATUS_HELP_MSG,
								Mi_DESELECT_ALL_BALLOON_HELP_MSG);

		appendSeparator();
		appendMenuItem(	Mi_DUPLICATE_MENUITEM_DISPLAY_NAME,	handler, 
								Mi_DUPLICATE_COMMAND_NAME,
								Mi_DUPLICATE_STATUS_HELP_MSG,
								Mi_NO_DUPLICATE_STATUS_HELP_MSG,
								Mi_DUPLICATE_BALLOON_HELP_MSG);
		}
	}

