
/*
 ***************************************************************************
 *                  Mica - the Java(tm) Graphics Framework                 *
 ***************************************************************************
 * NOTICE: Permission to use, copy, and modify this software and its       *
 * documentation is hereby granted provided that this notice appears in    *
 * all copies.                                                             *
 *                                                                         *
 * Permission to distribute un-modified copies of this software and its    *
 * documentation is hereby granted provided that no fee is charged and     *
 * that this notice appears in all copies.                                 *
 *                                                                         *
 * SOFTWARE FARM MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE          *
 * SUITABILITY OF THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT  *
 * NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR  *
 * A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. SOFTWARE FARM SHALL NOT BE   *
 * LIABLE TO ANY PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR       *
 * CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE, MODIFICATION OR           *
 * DISTRIBUTION OF THIS SOFTWARE OR ITS DERIVATIVES.                       *
 *                                                                         *
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, AND THE AUTHORS AND      *
 * DISTRIBUTORS HAVE NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT,        *
 * UPDATES, ENHANCEMENTS, OR MODIFICATIONS.                                *
 *                                                                         *
 ***************************************************************************
 *   Copyright (c) 1997-2004 Software Farm, Inc.  All Rights Reserved.     *
 ***************************************************************************
 */

package com.swfm.mica;

/**----------------------------------------------------------------------------------------------
 * This class makes a 'file' menu that is suitable for adding to a
 * MiEditorMenuBar. Each menu item has status bar and balloon help and
 * most have accelerators and mnemonics.
 * <p>
 * When a menu item is selected by the user one of the following commands
 * are generated:
 * <p>
 * <pre>
 *    Mi_NEW_COMMAND_NAME
 *    Mi_OPEN_COMMAND_NAME
 *    Mi_SAVE_COMMAND_NAME
 *    Mi_SAVE_AS_COMMAND_NAME
 *    Mi_CLOSE_COMMAND_NAME
 *    Mi_DISPLAY_PREFERENCES_COMMAND_NAME
 *    Mi_PRINT_SETUP_COMMAND_NAME
 *    Mi_PRINT_COMMAND_NAME
 *    Mi_QUIT_COMMAND_NAME
 * </pre>
 * @version     %I% %G%
 * @author      Michael L. Davis
 * @release 	1.4.1
 * @module 	%M%
 * @language	Java (JDK 1.4)
 *----------------------------------------------------------------------------------------------*/
public class MiFileMenu extends MiEditorMenu implements MiiCommandNames, MiiMessages
	{
					/**------------------------------------------------------
	 				 * Constructs a new MiFileMenu which will send commands
					 * generated by the menu to the given command handler.
					 * @param handler	 the command handler
					 * @see 		MiFileMenuCommands
					 *------------------------------------------------------*/
	public				MiFileMenu(MiiCommandHandler handler, MiiCommandManager manager)
		{
		super(Mi_FILE_MENU_DISPLAY_NAME, manager);

		handler = new MiFileMenuCommands(handler, manager);

		setCommandHandler(handler);

		appendMenuItem(	Mi_NEW_MENUITEM_DISPLAY_NAME,	handler, 
								Mi_NEW_COMMAND_NAME,
								Mi_NEW_STATUS_HELP_MSG,
								Mi_NO_NEW_STATUS_HELP_MSG,
								Mi_NEW_BALLOON_HELP_MSG);

		appendMenuItem(	Mi_OPEN_MENUITEM_DISPLAY_NAME,	handler, 
								Mi_OPEN_COMMAND_NAME,
								Mi_OPEN_STATUS_HELP_MSG,
								Mi_NO_OPEN_STATUS_HELP_MSG,
								Mi_OPEN_BALLOON_HELP_MSG);
		appendSeparator();
		appendMenuItem(	Mi_SAVE_MENUITEM_DISPLAY_NAME,	handler, 
								Mi_SAVE_COMMAND_NAME,
								Mi_SAVE_STATUS_HELP_MSG,
								Mi_NO_SAVE_STATUS_HELP_MSG,
								Mi_SAVE_BALLOON_HELP_MSG);

		appendMenuItem(	Mi_SAVE_AS_MENUITEM_DISPLAY_NAME, handler, 
								Mi_SAVE_AS_COMMAND_NAME,
								Mi_SAVE_AS_STATUS_HELP_MSG,
								Mi_NO_SAVE_AS_STATUS_HELP_MSG,
								Mi_SAVE_AS_BALLOON_HELP_MSG);
		appendSeparator();
		appendMenuItem(	Mi_CLOSE_MENUITEM_DISPLAY_NAME,	handler, 
								Mi_CLOSE_COMMAND_NAME,
								Mi_CLOSE_STATUS_HELP_MSG,
								Mi_NO_CLOSE_STATUS_HELP_MSG,
								Mi_CLOSE_BALLOON_HELP_MSG);
		appendSeparator();
		appendMenuItem(	Mi_PREFERENCES_MENUITEM_DISPLAY_NAME,
							handler, 
							Mi_DISPLAY_PREFERENCES_COMMAND_NAME,
							Mi_DISPLAY_PREFERENCES_STATUS_HELP_MSG,
							Mi_NO_DISPLAY_PREFERENCES_STATUS_HELP_MSG,
							Mi_DISPLAY_PREFERENCES_BALLOON_HELP_MSG);

		appendMenuItem(	Mi_PRINT_SETUP_MENUITEM_DISPLAY_NAME,
								handler, 
								Mi_PRINT_SETUP_COMMAND_NAME,
								Mi_PRINT_SETUP_STATUS_HELP_MSG,
								Mi_NO_PRINT_SETUP_STATUS_HELP_MSG,
								Mi_PRINT_SETUP_BALLOON_HELP_MSG);

		appendMenuItem(	Mi_PRINT_MENUITEM_DISPLAY_NAME,	handler, 
								Mi_PRINT_COMMAND_NAME,
								Mi_PRINT_STATUS_HELP_MSG,
								Mi_NO_PRINT_STATUS_HELP_MSG,
								Mi_PRINT_BALLOON_HELP_MSG);
		appendSeparator();
		appendMenuItem(	Mi_QUIT_MENUITEM_DISPLAY_NAME,	handler, 
								Mi_QUIT_COMMAND_NAME,
								Mi_QUIT_STATUS_HELP_MSG,
								Mi_NO_QUIT_STATUS_HELP_MSG,
								Mi_QUIT_BALLOON_HELP_MSG);
		}
	}

