
/*
 ***************************************************************************
 *                  Mica - the Java(tm) Graphics Framework                 *
 ***************************************************************************
 * NOTICE: Permission to use, copy, and modify this software and its       *
 * documentation is hereby granted provided that this notice appears in    *
 * all copies.                                                             *
 *                                                                         *
 * Permission to distribute un-modified copies of this software and its    *
 * documentation is hereby granted provided that no fee is charged and     *
 * that this notice appears in all copies.                                 *
 *                                                                         *
 * SOFTWARE FARM MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE          *
 * SUITABILITY OF THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT  *
 * NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR  *
 * A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. SOFTWARE FARM SHALL NOT BE   *
 * LIABLE TO ANY PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR       *
 * CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE, MODIFICATION OR           *
 * DISTRIBUTION OF THIS SOFTWARE OR ITS DERIVATIVES.                       *
 *                                                                         *
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, AND THE AUTHORS AND      *
 * DISTRIBUTORS HAVE NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT,        *
 * UPDATES, ENHANCEMENTS, OR MODIFICATIONS.                                *
 *                                                                         *
 ***************************************************************************
 *   Copyright (c) 1997-2004 Software Farm, Inc.  All Rights Reserved.     *
 ***************************************************************************
 */

package com.swfm.mica;

/**----------------------------------------------------------------------------------------------
 * This class makes a 'format' menu that is suitable for adding to a
 * MiEditorMenuBar. Each menu item has status bar and balloon help and
 * most have accelerators and mnemonics.
 * <p>
 * When a menu item is selected by the user one of the following commands
 * are generated:
 * <p>
 * <pre>
 *    Mi_FORMAT_COMMAND_NAME
 *    Mi_EXPAND_EDITING_AREA_COMMAND_NAME
 *    Mi_SHRINK_EDITING_AREA_COMMAND_NAME
 * </pre>
 * @version     %I% %G%
 * @author      Michael L. Davis
 * @release 	1.4.1
 * @module 	%M%
 * @language	Java (JDK 1.4)
 *----------------------------------------------------------------------------------------------*/
public class MiFormatMenu extends MiEditorMenu implements MiiCommandNames, MiiMessages
	{
					/**------------------------------------------------------
	 				 * Constructs a new MiFormatMenu, forwarding commands generated
					 * by this menu to an instance of MiFormatMenuCommands.
					 * @see			MiFormatMenuCommands
					 *------------------------------------------------------*/
	public				MiFormatMenu(MiiCommandManager manager)
		{
		this(new MiFormatMenuCommands(manager), manager);
		}
					/**------------------------------------------------------
	 				 * Constructs a new MiFormatMenu which will send commands
					 * generated by the menu to the given command handler.
					 * @param handler	the command handler
					 * @see 		MiFormatMenuCommands
					 *------------------------------------------------------*/
	public				MiFormatMenu(MiiCommandHandler handler, MiiCommandManager manager)
		{
		super(Mi_FORMAT_MENU_DISPLAY_NAME, manager);

		setCommandHandler(handler);

		appendMenuItem(	Mi_FORMAT_MENUITEM_DISPLAY_NAME,
						handler, Mi_FORMAT_COMMAND_NAME,
						Mi_FORMAT_STATUS_HELP_MSG,
						Mi_NO_FORMAT_STATUS_HELP_MSG,
						Mi_FORMAT_BALLOON_HELP_MSG);

		appendMenuItem(	Mi_EXPAND_EDITING_AREA_MENUITEM_DISPLAY_NAME,
						handler, Mi_EXPAND_EDITING_AREA_COMMAND_NAME,
						Mi_EXPAND_EDITING_AREA_STATUS_HELP_MSG,
						Mi_NO_EXPAND_EDITING_AREA_STATUS_HELP_MSG,
						Mi_EXPAND_EDITING_AREA_BALLOON_HELP_MSG);

		appendMenuItem(	Mi_SHRINK_EDITING_AREA_MENUITEM_DISPLAY_NAME,
						handler, Mi_SHRINK_EDITING_AREA_COMMAND_NAME,
						Mi_SHRINK_EDITING_AREA_STATUS_HELP_MSG,
						Mi_NO_SHRINK_EDITING_AREA_STATUS_HELP_MSG,
						Mi_SHRINK_EDITING_AREA_BALLOON_HELP_MSG);
		}
	}

