
/*
 ***************************************************************************
 *                  Mica - the Java(tm) Graphics Framework                 *
 ***************************************************************************
 * NOTICE: Permission to use, copy, and modify this software and its       *
 * documentation is hereby granted provided that this notice appears in    *
 * all copies.                                                             *
 *                                                                         *
 * Permission to distribute un-modified copies of this software and its    *
 * documentation is hereby granted provided that no fee is charged and     *
 * that this notice appears in all copies.                                 *
 *                                                                         *
 * SOFTWARE FARM MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE          *
 * SUITABILITY OF THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT  *
 * NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR  *
 * A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. SOFTWARE FARM SHALL NOT BE   *
 * LIABLE TO ANY PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR       *
 * CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE, MODIFICATION OR           *
 * DISTRIBUTION OF THIS SOFTWARE OR ITS DERIVATIVES.                       *
 *                                                                         *
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, AND THE AUTHORS AND      *
 * DISTRIBUTORS HAVE NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT,        *
 * UPDATES, ENHANCEMENTS, OR MODIFICATIONS.                                *
 *                                                                         *
 ***************************************************************************
 *   Copyright (c) 1997-2004 Software Farm, Inc.  All Rights Reserved.     *
 ***************************************************************************
 */

package com.swfm.mica;

/**----------------------------------------------------------------------------------------------
 * This class makes a 'help' menu that is suitable for adding to a
 * MiEditorMenuBar. Each menu item has status bar and balloon help and
 * most have accelerators and mnemonics.
 * <p>
 * When a menu item is selected by the user one of the following commands
 * are generated:
 * <p>
 * <pre>
 *    Mi_DISPLAY_ABOUT_DIALOG_COMMAND_NAME
 *    Mi_HELP_ON_APPLICATION_COMMAND_NAME
 *    Mi_ENABLE_BALLOON_HELP_COMMAND_NAME
 *    Mi_DISABLE_BALLOON_HELP_COMMAND_NAME
 *    Mi_ENABLE_TOOLHINT_HELP_COMMAND_NAME
 *    Mi_DISABLE_TOOLHINT_HELP_COMMAND_NAME
 * </pre>
 * @version     %I% %G%
 * @author      Michael L. Davis
 * @release 	1.4.1
 * @module 	%M%
 * @language	Java (JDK 1.4)
 *----------------------------------------------------------------------------------------------*/
public class MiHelpMenu extends MiEditorMenu implements MiiCommandNames, MiiMessages
	{
					/**------------------------------------------------------
	 				 * Constructs a new MiHelpMenu, forwarding commands generated
					 * by this menu to an instance of MiHelpMenuCommands.
					 * @see			MiHelpMenuCommands
					 *------------------------------------------------------*/
	public				MiHelpMenu(MiiCommandManager manager)
		{
		this(new MiHelpMenuCommands(manager), manager);
		}
					/**------------------------------------------------------
	 				 * Constructs a new MiHelpMenu which will send commands
					 * generated by the menu to the given command handler.
					 * @param handler	 the command handler
					 * @see 		MiHelpMenuCommands
					 *------------------------------------------------------*/
	public				MiHelpMenu(MiiCommandHandler handler, MiiCommandManager manager)
		{
		super(Mi_HELP_MENU_DISPLAY_NAME, manager);

		setCommandHandler(handler);

		appendMenuItem(		"About...", 		handler, 
								Mi_DISPLAY_ABOUT_DIALOG_COMMAND_NAME);
		appendMenuItem(		"Help Topics...", 	handler, 
								Mi_HELP_ON_APPLICATION_COMMAND_NAME);
/*
		appendSeparator();
		appendBooleanMenuItem(	"Balloon Help",	 	handler, 
								Mi_ENABLE_BALLOON_HELP_COMMAND_NAME,
								Mi_DISABLE_BALLOON_HELP_COMMAND_NAME);
		appendBooleanMenuItem(	"Tool Hints", 		handler, 
								Mi_ENABLE_TOOLHINT_HELP_COMMAND_NAME,
								Mi_DISABLE_TOOLHINT_HELP_COMMAND_NAME);
*/

		setHelpMessages(Mi_DISPLAY_ABOUT_DIALOG_COMMAND_NAME,
				Mi_DISPLAY_ABOUT_DIALOG_STATUS_HELP_MSG,
				Mi_NO_DISPLAY_ABOUT_DIALOG_STATUS_HELP_MSG,
				Mi_DISPLAY_ABOUT_DIALOG_BALLOON_HELP_MSG);

		setHelpMessages(Mi_HELP_ON_APPLICATION_COMMAND_NAME,
				Mi_HELP_ON_APPLICATION_STATUS_HELP_MSG,
				Mi_NO_HELP_ON_APPLICATION_STATUS_HELP_MSG,
				Mi_HELP_ON_APPLICATION_BALLOON_HELP_MSG);

/*
		setHelpMessages(Mi_ENABLE_BALLOON_HELP_COMMAND_NAME,
				Mi_ENABLE_BALLOON_HELP_STATUS_HELP_MSG,
				Mi_NO_ENABLE_BALLOON_HELP_STATUS_HELP_MSG,
				Mi_ENABLE_BALLOON_HELP_BALLOON_HELP_MSG);
		setHelpMessages(Mi_ENABLE_TOOLHINT_HELP_COMMAND_NAME,
				Mi_ENABLE_TOOLHINT_HELP_STATUS_HELP_MSG,
				Mi_NO_ENABLE_TOOLHINT_HELP_STATUS_HELP_MSG,
				Mi_ENABLE_TOOLHINT_HELP_BALLOON_HELP_MSG);
*/
		}
	}

