
/*
 ***************************************************************************
 *                  Mica - the Java(tm) Graphics Framework                 *
 ***************************************************************************
 * NOTICE: Permission to use, copy, and modify this software and its       *
 * documentation is hereby granted provided that this notice appears in    *
 * all copies.                                                             *
 *                                                                         *
 * Permission to distribute un-modified copies of this software and its    *
 * documentation is hereby granted provided that no fee is charged and     *
 * that this notice appears in all copies.                                 *
 *                                                                         *
 * SOFTWARE FARM MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE          *
 * SUITABILITY OF THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT  *
 * NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR  *
 * A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. SOFTWARE FARM SHALL NOT BE   *
 * LIABLE TO ANY PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR       *
 * CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE, MODIFICATION OR           *
 * DISTRIBUTION OF THIS SOFTWARE OR ITS DERIVATIVES.                       *
 *                                                                         *
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, AND THE AUTHORS AND      *
 * DISTRIBUTORS HAVE NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT,        *
 * UPDATES, ENHANCEMENTS, OR MODIFICATIONS.                                *
 *                                                                         *
 ***************************************************************************
 *   Copyright (c) 1997-2004 Software Farm, Inc.  All Rights Reserved.     *
 ***************************************************************************
 */


package com.swfm.mica;

/**----------------------------------------------------------------------------------------------
 * This class makes a 'layout' menu that is suitable for adding to a
 * MiEditorMenuBar. Each menu item has status bar and balloon help and
 * most have accelerators and mnemonics.
 * <p>
 * When a menu item is selected by the user one of the following commands
 * are generated:
 * <p>
 * <pre>
 *    Mi_ARRANGE_GRID_COMMAND_NAME
 *    Mi_ARRANGE_ROW_COMMAND_NAME
 *    Mi_ARRANGE_COLUMN_COMMAND_NAME
 *    Mi_SAME_WIDTH_COMMAND_NAME
 *    Mi_SAME_HEIGHT_COMMAND_NAME
 *    Mi_ALIGN_BOTTOM_COMMAND_NAME
 *    Mi_ALIGN_TOP_COMMAND_NAME
 *    Mi_ALIGN_LEFT_COMMAND_NAME
 *    Mi_ALIGN_RIGHT_COMMAND_NAME
 *    Mi_FORMAT_GRID_COMMAND_NAME
 *    Mi_FORMAT_ROW_COMMAND_NAME
 *    Mi_FORMAT_BJ_ROW_COMMAND_NAME
 *    Mi_FORMAT_TJ_ROW_COMMAND_NAME
 *    Mi_FORMAT_COLUMN_COMMAND_NAME
 *    Mi_FORMAT_LJ_COLUMN_COMMAND_NAME
 *    Mi_FORMAT_RJ_COLUMN_COMMAND_NAME
 *    Mi_REMOVE_FORMAT_COMMAND_NAME
 * </pre>
 * @see     	MiLayoutMenuCommands
 * @see     	MiGraphMenu
 * @version     %I% %G%
 * @author      Michael L. Davis
 * @release 	1.4.1
 * @module 	%M%
 * @language	Java (JDK 1.4)
 *----------------------------------------------------------------------------------------------*/
public class MiLayoutMenu extends MiEditorMenu implements MiiCommandNames, MiiMessages, MiiPartsDefines, MiiDisplayNames
	{
					/**------------------------------------------------------
	 				 * Constructs a new MiLayoutMenu, forwarding commands generated
					 * by this menu to an instance of MiLayoutMenuCommands.
					 * @see			MiLayoutMenuCommands
					 *------------------------------------------------------*/
	public				MiLayoutMenu(MiiCommandManager manager)
		{
		this(new MiLayoutMenuCommands(manager), manager);
		}
					/**------------------------------------------------------
	 				 * Constructs a new MiLayoutMenu which will send commands
					 * generated by the menu to the given command handler.
					 * @param handler	the command handler
					 * @see 		MiLayoutMenuCommands
					 *------------------------------------------------------*/
	public				MiLayoutMenu(MiiCommandHandler handler, MiiCommandManager manager)
		{
		super(Mi_LAYOUT_MENU_DISPLAY_NAME, manager);

		setCommandHandler(handler);

		appendMenuItem(		Mi_ARRANGE_GRID_DISPLAY_NAME, 	handler, 
									Mi_ARRANGE_GRID_COMMAND_NAME,
									Mi_ARRANGE_GRID_STATUS_HELP_MSG,
									Mi_NO_ARRANGE_GRID_STATUS_HELP_MSG,
									Mi_ARRANGE_GRID_BALLOON_HELP_MSG);
		appendMenuItem(		Mi_ARRANGE_ROW_DISPLAY_NAME, 	handler, 
									Mi_ARRANGE_ROW_COMMAND_NAME,
									Mi_ARRANGE_ROW_STATUS_HELP_MSG,
									Mi_NO_ARRANGE_ROW_STATUS_HELP_MSG,
									Mi_ARRANGE_ROW_BALLOON_HELP_MSG);
		appendMenuItem(		Mi_ARRANGE_COLUMN_DISPLAY_NAME,	handler, 
									Mi_ARRANGE_COLUMN_COMMAND_NAME,
									Mi_ARRANGE_COLUMN_STATUS_HELP_MSG,
									Mi_NO_ARRANGE_COLUMN_STATUS_HELP_MSG,
									Mi_ARRANGE_COLUMN_BALLOON_HELP_MSG);
		appendSeparator();
		appendMenuItem(		Mi_SAME_WIDTH_DISPLAY_NAME,	handler, 
									Mi_SAME_WIDTH_COMMAND_NAME,
									Mi_SAME_WIDTH_STATUS_HELP_MSG,
									Mi_NO_SAME_WIDTH_STATUS_HELP_MSG,
									Mi_SAME_WIDTH_BALLOON_HELP_MSG);
		appendMenuItem(		Mi_SAME_HEIGHT_DISPLAY_NAME, 	handler, 
									Mi_SAME_HEIGHT_COMMAND_NAME,
									Mi_SAME_HEIGHT_STATUS_HELP_MSG,
									Mi_NO_SAME_HEIGHT_STATUS_HELP_MSG,
									Mi_SAME_HEIGHT_BALLOON_HELP_MSG);
		appendSeparator();
		appendMenuItem(		Mi_ALIGN_BOTTOM_DISPLAY_NAME, 	handler, 
									Mi_ALIGN_BOTTOM_COMMAND_NAME,
									Mi_ALIGN_BOTTOM_STATUS_HELP_MSG,
									Mi_NO_ALIGN_BOTTOM_STATUS_HELP_MSG,
									Mi_ALIGN_BOTTOM_BALLOON_HELP_MSG);
		appendMenuItem(		Mi_ALIGN_TOP_DISPLAY_NAME, 	handler, 
									Mi_ALIGN_TOP_COMMAND_NAME,
									Mi_ALIGN_TOP_STATUS_HELP_MSG,
									Mi_NO_ALIGN_TOP_STATUS_HELP_MSG,
									Mi_ALIGN_TOP_BALLOON_HELP_MSG);
		appendMenuItem(		Mi_ALIGN_LEFT_DISPLAY_NAME, 	handler, 
									Mi_ALIGN_LEFT_COMMAND_NAME,
									Mi_ALIGN_LEFT_STATUS_HELP_MSG,
									Mi_NO_ALIGN_LEFT_STATUS_HELP_MSG,
									Mi_ALIGN_LEFT_BALLOON_HELP_MSG);
		appendMenuItem(		Mi_ALIGN_RIGHT_DISPLAY_NAME, 	handler, 
									Mi_ALIGN_RIGHT_COMMAND_NAME,
									Mi_ALIGN_RIGHT_STATUS_HELP_MSG,
									Mi_NO_ALIGN_RIGHT_STATUS_HELP_MSG,
									Mi_ALIGN_RIGHT_BALLOON_HELP_MSG);
		appendSeparator();
		appendMenuItem(		Mi_FORMAT_GRID_DISPLAY_NAME, 	handler, 
									Mi_FORMAT_GRID_COMMAND_NAME,
									Mi_FORMAT_GRID_STATUS_HELP_MSG,
									Mi_NO_FORMAT_GRID_STATUS_HELP_MSG,
									Mi_FORMAT_GRID_BALLOON_HELP_MSG);
		appendMenuItem(		Mi_FORMAT_ROW_DISPLAY_NAME, 	handler, 
									Mi_FORMAT_ROW_COMMAND_NAME,
									Mi_FORMAT_ROW_STATUS_HELP_MSG,
									Mi_NO_FORMAT_ROW_STATUS_HELP_MSG,
									Mi_FORMAT_ROW_BALLOON_HELP_MSG);
		appendMenuItem(		Mi_FORMAT_BJ_ROW_DISPLAY_NAME, 	handler, 
									Mi_FORMAT_BJ_ROW_COMMAND_NAME,
									Mi_FORMAT_BJ_ROW_STATUS_HELP_MSG,
									Mi_NO_FORMAT_BJ_ROW_STATUS_HELP_MSG,
									Mi_FORMAT_BJ_ROW_BALLOON_HELP_MSG);
		appendMenuItem(		Mi_FORMAT_TJ_ROW_DISPLAY_NAME, 	handler, 
									Mi_FORMAT_TJ_ROW_COMMAND_NAME,
									Mi_FORMAT_TJ_ROW_STATUS_HELP_MSG,
									Mi_NO_FORMAT_TJ_ROW_STATUS_HELP_MSG,
									Mi_FORMAT_TJ_ROW_BALLOON_HELP_MSG);
		appendMenuItem(		Mi_FORMAT_COLUMN_DISPLAY_NAME, 	handler, 
									Mi_FORMAT_COLUMN_COMMAND_NAME,
									Mi_FORMAT_COLUMN_STATUS_HELP_MSG,
									Mi_NO_FORMAT_COLUMN_STATUS_HELP_MSG,
									Mi_FORMAT_COLUMN_BALLOON_HELP_MSG);
		appendMenuItem(		Mi_FORMAT_LJ_COLUMN_DISPLAY_NAME, handler, 
									Mi_FORMAT_LJ_COLUMN_COMMAND_NAME,
									Mi_FORMAT_LJ_COLUMN_STATUS_HELP_MSG,
									Mi_NO_FORMAT_LJ_COLUMN_STATUS_HELP_MSG,
									Mi_FORMAT_LJ_COLUMN_BALLOON_HELP_MSG);
		appendMenuItem(		Mi_FORMAT_RJ_COLUMN_DISPLAY_NAME, handler, 
									Mi_FORMAT_RJ_COLUMN_COMMAND_NAME,
									Mi_FORMAT_RJ_COLUMN_STATUS_HELP_MSG,
									Mi_NO_FORMAT_RJ_COLUMN_STATUS_HELP_MSG,
									Mi_FORMAT_RJ_COLUMN_BALLOON_HELP_MSG);
		appendSeparator();
		appendMenuItem(		Mi_REMOVE_FORMAT_DISPLAY_NAME, 	handler, 
									Mi_REMOVE_FORMAT_COMMAND_NAME,
									Mi_REMOVE_FORMAT_STATUS_HELP_MSG,
									Mi_NO_REMOVE_FORMAT_STATUS_HELP_MSG,
									Mi_REMOVE_FORMAT_BALLOON_HELP_MSG);
		}
	}

