
/*
 ***************************************************************************
 *                  Mica - the Java(tm) Graphics Framework                 *
 ***************************************************************************
 * NOTICE: Permission to use, copy, and modify this software and its       *
 * documentation is hereby granted provided that this notice appears in    *
 * all copies.                                                             *
 *                                                                         *
 * Permission to distribute un-modified copies of this software and its    *
 * documentation is hereby granted provided that no fee is charged and     *
 * that this notice appears in all copies.                                 *
 *                                                                         *
 * SOFTWARE FARM MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE          *
 * SUITABILITY OF THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT  *
 * NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR  *
 * A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. SOFTWARE FARM SHALL NOT BE   *
 * LIABLE TO ANY PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR       *
 * CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE, MODIFICATION OR           *
 * DISTRIBUTION OF THIS SOFTWARE OR ITS DERIVATIVES.                       *
 *                                                                         *
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, AND THE AUTHORS AND      *
 * DISTRIBUTORS HAVE NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT,        *
 * UPDATES, ENHANCEMENTS, OR MODIFICATIONS.                                *
 *                                                                         *
 ***************************************************************************
 *   Copyright (c) 1997-2004 Software Farm, Inc.  All Rights Reserved.     *
 ***************************************************************************
 */


package com.swfm.mica;

/**----------------------------------------------------------------------------------------------
 * This class makes a 'shape popup' menu that is suitable for adding to shapes
 * as their context menu. Each menu item has status bar and balloon help and
 * most have accelerators and mnemonics.
 * <p>
 * When a menu item is selected by the user one of the following commands
 * are generated:
 * <p>
 * <pre>
 *    Mi_CUT_COMMAND_NAME
 *    Mi_COPY_COMMAND_NAME
 *    Mi_DELETE_COMMAND_NAME
 *    Mi_DUPLICATE_COMMAND_NAME
 *    Mi_DISCONNECT_COMMAND_NAME
 *    Mi_BRING_TO_FRONT_COMMAND_NAME
 *    Mi_SEND_TO_BACK_COMMAND_NAME
 *    Mi_SEND_BACKWARD_COMMAND_NAME
 *    Mi_DISPLAY_PROPERTIES_COMMAND_NAME
 * </pre>
 * @see		MiiContextMenu
 * @see		MiPart#setContextMenu
 * @version     %I% %G%
 * @author      Michael L. Davis
 * @release 	1.4.1
 * @module 	%M%
 * @language	Java (JDK 1.4)
 *----------------------------------------------------------------------------------------------*/
public class MiShapePopupMenu extends MiEditorMenu implements MiiCommandNames, MiiMessages
	{
					/**------------------------------------------------------
	 				 * Constructs a new MiShapePopupMenu, forwarding commands
					 * generated by this menu to an instance of 
					 * MiShapePopupMenuCommands. Creates a default command 
					 * manager that handles sensitivity and state of the
					 * various options in this menu. 
					 *			and state.
					 * @see			MiShapePopupMenuCommands
					 * @see			#getCommandManager
					 *------------------------------------------------------*/
	public				MiShapePopupMenu()
		{
		this(new MiCommandManager());
		}
					/**------------------------------------------------------
	 				 * Constructs a new MiShapePopupMenu, forwarding commands
					 * generated by this menu to an instance of 
					 * MiShapePopupMenuCommands.
					 * @param manager	the command manager that handles sensitivity
					 *			and state.
					 * @see			MiShapePopupMenuCommands
					 *------------------------------------------------------*/
	public				MiShapePopupMenu(MiiCommandManager manager)
		{
		this(new MiShapePopupMenuCommands(manager), manager);
		}
					/**------------------------------------------------------
	 				 * Constructs a new MiShapePopupMenu which will send commands
					 * generated by the menu to the given command handler.
					 * @param handler	the command handler
					 * @param manager	the command manager that handles sensitivity
					 *			and state.
					 * @see 		MiShapePopupMenuCommands
					 *------------------------------------------------------*/
	public				MiShapePopupMenu(MiiCommandHandler handler, MiiCommandManager manager)
		{
		super("Shape Popup", manager);

		setCommandHandler(handler);

		appendMenuItem(		"Cu&t\t^X", 		handler, 
								Mi_CUT_COMMAND_NAME);
		appendMenuItem(		"&Copy\t^C", 		handler, 
								Mi_COPY_COMMAND_NAME);
		appendMenuItem(		"&Delete\tdelete", 	handler, 
								Mi_DELETE_COMMAND_NAME);
		appendSeparator();
		appendMenuItem(		"Du&plicate", 		handler, 
								Mi_DUPLICATE_COMMAND_NAME);
		appendMenuItem(		"Disconnec&t", 		handler, 
								Mi_DISCONNECT_COMMAND_NAME);
		appendSeparator();
		appendMenuItem(		"Bring to &Front\t^F", 	handler, 
								Mi_BRING_TO_FRONT_COMMAND_NAME);
		appendMenuItem(		"Send to &Back\t^B",	handler, 
								Mi_SEND_TO_BACK_COMMAND_NAME);
		appendMenuItem(		"Bring Forward", 	handler, 
								Mi_BRING_FORWARD_COMMAND_NAME);
		appendMenuItem(		"Send Backward",	handler, 
								Mi_SEND_BACKWARD_COMMAND_NAME);
		appendSeparator();
		appendMenuItem(		"&Properties\t^Enter", 	handler, 
								Mi_DISPLAY_PROPERTIES_COMMAND_NAME);

		setHelpMessages(Mi_CUT_COMMAND_NAME,
				Mi_CUT_STATUS_HELP_MSG,
				Mi_NO_CUT_STATUS_HELP_MSG,
				Mi_CUT_BALLOON_HELP_MSG);

		setHelpMessages(Mi_COPY_COMMAND_NAME,
				Mi_COPY_STATUS_HELP_MSG,
				Mi_NO_COPY_STATUS_HELP_MSG,
				Mi_COPY_BALLOON_HELP_MSG);

		setHelpMessages(Mi_DELETE_COMMAND_NAME,
				Mi_DELETE_STATUS_HELP_MSG,
				Mi_NO_DELETE_STATUS_HELP_MSG,
				Mi_DELETE_BALLOON_HELP_MSG);

		setHelpMessages(Mi_DUPLICATE_COMMAND_NAME,
				Mi_DUPLICATE_STATUS_HELP_MSG,
				Mi_NO_DUPLICATE_STATUS_HELP_MSG,
				Mi_DUPLICATE_BALLOON_HELP_MSG);

		setHelpMessages(Mi_DISCONNECT_COMMAND_NAME,
				Mi_DISCONNECT_STATUS_HELP_MSG,
				Mi_NO_DISCONNECT_STATUS_HELP_MSG,
				Mi_DISCONNECT_BALLOON_HELP_MSG);

		setHelpMessages(Mi_BRING_TO_FRONT_COMMAND_NAME,
				Mi_BRING_TO_FRONT_STATUS_HELP_MSG,
				Mi_NO_BRING_TO_FRONT_STATUS_HELP_MSG,
				Mi_BRING_TO_FRONT_BALLOON_HELP_MSG);

		setHelpMessages(Mi_SEND_TO_BACK_COMMAND_NAME,
				Mi_SEND_TO_BACK_STATUS_HELP_MSG,
				Mi_NO_SEND_TO_BACK_STATUS_HELP_MSG,
				Mi_SEND_TO_BACK_BALLOON_HELP_MSG);

		setHelpMessages(Mi_BRING_FORWARD_COMMAND_NAME,
				Mi_BRING_FORWARD_STATUS_HELP_MSG,
				Mi_NO_BRING_FORWARD_STATUS_HELP_MSG,
				Mi_BRING_FORWARD_BALLOON_HELP_MSG);

		setHelpMessages(Mi_SEND_BACKWARD_COMMAND_NAME,
				Mi_SEND_BACKWARD_STATUS_HELP_MSG,
				Mi_NO_SEND_BACKWARD_STATUS_HELP_MSG,
				Mi_SEND_BACKWARD_BALLOON_HELP_MSG);

		setHelpMessages(Mi_DISPLAY_PROPERTIES_COMMAND_NAME,
				Mi_DISPLAY_PROPERTIES_STATUS_HELP_MSG,
				Mi_NO_DISPLAY_PROPERTIES_STATUS_HELP_MSG,
				Mi_DISPLAY_PROPERTIES_BALLOON_HELP_MSG);
		}
					/**------------------------------------------------------
	 				 * Gets whether this popup should select the target shape
					 * when it pops up.
					 * @return 		always returns true
					 * @implements 		MiiContextMenu#getToSelectAttributedShape
					 *------------------------------------------------------*/
	public		boolean		getToSelectAttributedShape()
		{
		return(true);
		}
	}

